pyz_test: Add licenses attribute for use in third_party
Rules in third_party need licenses or they cause the following error.
Add third_party/tests to test all the rules to make sure they work.

ERROR: third_party/tests/BUILD:4:1: third-party rule
'//third_party/tests:licenses_test_deps' lacks a license declaration
with one of the following types: notice, reciprocal, permissive,
restricted, unencumbered, by_exception_only